### ISSUE TITLE
Score not significantly improved

### ISSUE THREAD

**Issue by 2black0** [MehdiShahbazi/Webots-reinforcement-navigation#1]
![image](https://github.com/MehdiShahbazi/Webots-reinforcement-navigation/assets/9410351/00ade0cb-d724-487b-9030-7150216fde75)

Below I have attached the training process for 6600 episodes with a total of 20000 episodes. The score results did not improve significantly, is this normal?

if I read in the readme, even 2000 episodes of robots can reach the finish point

**Comment by MehdiShahbazi** [comment]
Sorry for the late response.
I have re-tested the code, and everything seems fine. I've attached a GIF that shows the agent in the training phase, and it demonstrates that the agent is learning to solve the problem even before episode 1500. Additionally, I’ve included the new run result plot demonstrating the rewards received during training.


<img src="https://github.com/user-attachments/assets/05eb5a3e-d390-44bb-bf7c-a5504847933b" width="75%" />
<img src="https://github.com/user-attachments/assets/a86b1fdf-b322-4684-b46b-e4abf8452af3" width="75%" />
<img src="https://github.com/user-attachments/assets/9e289730-53bf-4282-972e-e8ce5ef1f037" width="75%" />



I am closing this issue as the answer has been provided.

**Comment by MehdiShahbazi** [comment]
I am closing this issue as the answer has been provided.
